export const ACTION_TYPE_SUCCESS = "SUCCESS";
export const ACTION_TYPE_ERROR = "ERROR";
export const ACTION_TYPE_WARNING = "WARNING";
export const ACTION_TYPE_LOADING = "LOADING";
export const ACTION_TYPE_ADD_VIDEO_TO_PLAYLIST = "ADD_VIDEO_TO_PLAYLIST";
export const ACTION_TYPE_REMOVE_VIDEO_FROM_PLAYLIST =
  "REMOVE_VIDEO_FROM_PLAYLIST";
